### ISSUE TITLE
Make port used by tinyssh / dropbear configurable

### ISSUE THREAD

**Issue by Zeitwaechter** [wolegis/mkinitcpio-systemd-extras#2]
Dear @wolegis ,

today I stumbled upon this package when setting up another client with ssh login on boot, to enter a passphrase.

Let me open up with saying my thanks, as I have directly amended my public [Arch Linux setup gist](https://gist.github.com/Zeitwaechter/c2de35b21b826d0f261a55bad8b9ece4#enable-remote-ssh-system-drive-decryption-on-boot-level) and replaced my old stuff with the new setup, refering to this package of yours.

There are but two things I humbly wanted to reach out to you about, in requesting if you can make the [SSH port](https://github.com/wolegis/mkinitcpio-systemd-extras/blob/main/sd-tinyssh#L13) ~and providing some other `authorized_keys` , besides the one from [root](https://github.com/wolegis/mkinitcpio-systemd-extras/blob/main/sd-tinyssh#L45C76-L45C91), configurable~.

You may decide for yourself how much sense my requests do make, but port `22` is what I would normally only refer to for any _ssh tarpit_ ~and in my new setup gist I have (now still) to copy the `authorized_keys` of users  into the one from `root`~.

~Hm.. sure, while writing this, I could also think about an solution in where I would probably be able to manually convert said ed25519 ssh key via `tinyssh-convert` myself and might be able to just forward it to the `/etc/tinyssh/sshkeydir` directory, but... let me first hear what you think about any of my requests.~

Maybe I'm also just missing some insight and do stuff the wrong way?

Thanks in advance and cheers :raised_hands:

**Comment by wolegis** [comment]
Thanks for the positive feedback. Regarding your requests for enhancement:

1. Introducing another configuration option to specify an alternative SSH port shouldn't be too difficult. I doubt this will yield a significant gain in security, as it's just a little bit of *security by obscurity*. But it may come in handy some times to get around annoying firewall rules.
2. I'm a bit confused regarding the request about `authorized_keys`. You mention `/etc/tinyssh/sshkeydir`. This directory contains certificates totally distinct from those in any `authorized_keys`. The latter contain public keys used to authenticate clients, whereas `/etc/tinyssh/sshkeydir` contains private keys used to authenticate the server. Additionally you talk about *providing some other `authorized_keys` , besides the one from root*. Does this mean you want another user to be able to log into the initramfs environment? I'm inclined to reject this request. But first let's sort out all potential misunderstandings.

I'm going to focus this issue on the first request. May I kindly ask to open another issue about the `authorized_keys` topic.

**Comment by wolegis** [comment]
`SD_TINYSSH_PORT` and `SD_DROPBEAR_PORT` have been implemented with v0.5. Please review and give some feedback.

**Comment by Zeitwaechter** [comment]
Hey, thank you very much!

I updated my guide and it's working like a charm.
I'm sorry though with taking so long to reply and test it out.

Awesome, ticket's closed :+1: :+1:
