### ISSUE TITLE
Make it configurable which authorized_keys can be provided

### ISSUE THREAD

**Issue by Zeitwaechter** [wolegis/mkinitcpio-systemd-extras#3]
Dear @wolegis,

I would like to request if it would be feasable for you -and if it even makes sense- to make it configurable which `authorized_keys` can be provided when the `tinyssh` server is started via `sd-tinyssh` kernel param.

In my [current setup](https://gist.github.com/Zeitwaechter/c2de35b21b826d0f261a55bad8b9ece4#client) I'm updating the `authorized_keys` of `root` with the one of my "main" user, as I normaly don't use `root` from the get-go.

After the system is booted I also would then like to not being able to login as `root`, even with public key auth-only.

Of course, I could _just_ disable root login altogether,, via OpenSSH/`PermitRootLogin no`, which I mainly _do_ use, but it seems like there is [no such option](https://github.com/janmojzis/tinyssh/issues/3) with `tinyssh`(?).

So, if I'm right, and I sadly could not find a newer source than that one from 2015 on a quick search, it might at least be a "real" issue for others.

Would you be fine with such a change and can you see the use case or would you rather suggest me to deal with it with what OpenSSH gives me out of the box, as I would be fine that way, as `tinyssh` does ignore its configs?

Thank you very much in advance for any feedback.

I'm also totally fine with a decline :+1: 

Cheers!

**Comment by wolegis** [comment]
I think I got your intention. Please have a look at the [configuration of sd-dropbear](https://github.com/wolegis/mkinitcpio-systemd-extras/wiki/Dropbear-SSH-server#configuration). Can you confirm that the variable `SD_DROPBEAR_AUTHORIZED_KEYS` there is what you would like to have for sd-tinyssh?

**Comment by Zeitwaechter** [comment]
Ah, lovely!

I havn't seen this yet, as `sd-dropbear` was not in my focus, sorry.

Yes, something like this seems to be what I would like to request.
Would you be fine with such a change?

Thanks in advance for letting me know.

Cheers! :raised_hands:

**Comment by wolegis** [comment]
`SD_TINYSSH_AUTHORIZED_KEYS` has been implemented with v0.5. Please review and give me some feedback.

**Comment by Zeitwaechter** [comment]
Hey, thank you very much!

I updated my guide and it's working like a charm.
I'm sorry though with taking so long to reply and test it out.

Awesome, ticket's closed :+1: :+1:
