### ISSUE TITLE
SD_NETWORK_CONFIG says that the specified file does not exist despite existing

### ISSUE THREAD

**Issue by Glich440** [wolegis/mkinitcpio-systemd-extras#8]
`==> ERROR: /etc/systemd/initramfs-network does not exist`
```
cat /etc/systemd/initramfs-network
[Match]
MACAddress=XX:XX:XX:XX:XX:XX //replaced by the actual MAC address in the file

[Network]
DHCP=yes
```

mkinitcpio:
```
MODULES=()
BINARIES=()
FILES=()
HOOKS=(systemd autodetect plymouth microcode modconf kms keyboard sd-vconsole sd-network block sd-tinyssh sd-encrypt filesystems fsck)
SD_TINYSSH_COMMAND="systemd-tty-ask-password-agent --query --watch"
SD_NETWORK_CONFIG=/etc/systemd/initramfs-network
```

**Comment by Glich440** [comment]
never mind, I just read the actual file and figured out it was supposed to be folder, a clarification in the documentation would be helpful.

**Comment by wolegis** [comment]
@Glich440 Any input is always welcome - be it code-wise or documentation-wise. However, in this case I see no room for improvement. As the documentation states:

> `SD_NETWORK_CONFIG`: With this setting in your `/etc/mkinitcpio.conf` you can specify an alternative source **directory** where the configuration for `systemd-networkd` is copied from

Emphasis by me.

**Comment by Glich440** [comment]
```
    if [[ ! -d "$SD_NETWORK_CONFIG" ]]; then
        error "${SD_NETWORK_CONFIG} does not exist"
        return 1
    f
```
could be changed to something like
```
    if [[ ! -d "$SD_NETWORK_CONFIG" ]]; then
             if [[ ! -f "$SD_NETWORK_CONFIG" ]]; then
                 error "${SD_NETWORK_CONFIG} is not a folder"
             else
                 error "${SD_NETWORK_CONFIG} does not exist"
             fi
        return 1
    fi
```
